### ISSUE TITLE
编译找不到这个paxos_msg.pb.h，请问如何解决

### ISSUE THREAD

**Issue by starcrafty** [tencent-wechat/phxpaxos#10]
compilation terminated.
make: *** [/data/phxsql-master/third_party/phxpaxos/phxpaxos-3341807442ad2e220bef3600f7424467a49be55c/src/communicate/communicate.o] Error 1
In file included from /data/phxsql-master/third_party/phxpaxos/phxpaxos-3341807442ad2e220bef3600f7424467a49be55c/src/algorithm/base.h:25:0,
                 from /data/phxsql-master/third_party/phxpaxos/phxpaxos-3341807442ad2e220bef3600f7424467a49be55c/src/algorithm/acceptor.h:24,
                 from /data/phxsql-master/third_party/phxpaxos/phxpaxos-3341807442ad2e220bef3600f7424467a49be55c/src/algorithm/acceptor.cpp:22:
/data/phxsql-master/third_party/phxpaxos/phxpaxos-3341807442ad2e220bef3600f7424467a49be55c/src/comm/comm_include.h:24:28: fatal error: ./paxos_msg.pb.h: No such file or directory
 #include "./paxos_msg.pb.h"

**Comment by lynncui00** [comment]
请检查third_party目录的protobuf是否正确放置，检查protoc的运行是否有报错。

**Comment by starcrafty** [comment]
third_party目录的protobuf编译正常，放置在third_party下面，protoc是什么？

**Comment by lynncui00** [comment]
编译的时候有没有指定安装到当前目录？，否则会安装到usr/local目录。

**Comment by andrewrong** [comment]
@lynncui00  这个问题要如何解决，我现在已经把protobuf生成的lib,bin,include都放在了third_party/protobuf这个目录下面，请帮忙解决一下...
