### ISSUE TITLE
您好，我在编译的时候遇到了一些问题，下面是我的步骤，请问您知道哪一步有问题吗？

### ISSUE THREAD

**Issue by qiaojialingithub** [tencent-wechat/phxpaxos#11]
- 1
首先clong项目，加上--recursive参数
git clone --recursive https://github.com/tencent-wechat/phxpaxos.git
这步的log是

```
正克隆到 'phxpaxos'...
remote: Counting objects: 591, done.
remote: Total 591 (delta 0), reused 0 (delta 0), pack-reused 591
接收对象中: 100% (591/591), 439.80 KiB | 105.00 KiB/s, done.
处理 delta 中: 100% (338/338), done.
检查连接... 完成。
子模组 'third_party/glog' (https://github.com/google/glog) 未对路径 'third_party/glog' 注册
子模组 'third_party/gmock' (https://github.com/google/googlemock) 未对路径 'third_party/gmock' 注册
子模组 'third_party/leveldb' (https://github.com/google/leveldb) 未对路径 'third_party/leveldb' 注册
子模组 'third_party/protobuf' (https://github.com/google/protobuf) 未对路径 'third_party/protobuf' 注册
正克隆到 'third_party/glog'...
remote: Counting objects: 1420, done.
remote: Total 1420 (delta 0), reused 0 (delta 0), pack-reused 1420
接收对象中: 100% (1420/1420), 1.39 MiB | 221.00 KiB/s, done.
处理 delta 中: 100% (1013/1013), done.
检查连接... 完成。
子模组路径 'third_party/glog'：检出 'de6149ef8e67b064a433a8b88924fa9f606ad5d5'
检查连接... 完成。
子模组路径 'third_party/protobuf'：检出 'd4d13a4349e4e59d67f311185ddcc1890d956d7a'
```

- 2
然后继续./autoinstall.sh
这步每执行一次就提示一个目录不存在，
```
```/phxpaxos/third_party/protobuf/include/ not found
please make sure PROTOBUF has been placed on third party directory
还有protobuf/lib
glob/lib等大概四五个目录不存在
```
我手动创建了这些目录
再执行./autoinstall.sh就可以了

- 3
make，报错找不到paxos_msg.pb.h

我就去了phxpaxos/src/comm目录下面执行了下面这句话
` protoc --cpp_out=./ paxos_msg.proto `
生成了一些文件，包括paxos_msg.pb.h

- 4
再去根目录下make出现以下报错信息
```
phxpaxos/src/comm/./paxos_msg.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: 没有那个文件或目录
 #include <google/protobuf/stubs/common.h>
```

请问哪一步的哪个命令有问题呢? 请您指导一下，谢谢。

**Comment by lynncui00** [comment]
protobuf和leveldb都需要先单独编译，编译成功后这些include或lib目录会自动创建。如何编译protobuf和leveldb网上应该有很多资料。

**Comment by qiaojialingithub** [comment]
非常感谢您的指导！终于弄好了

为其他人提供参考，步骤如下：
git clone --recursive https://github.com/tencent-wechat/phxpaxos.git

但是这个clone下来的protobuf好像编译不通过。
需要单独clone一下protobuf项目，编译安装，网上有教程，安好后默认在/usr/local下，把/usr/local下的bin include lib目录拷贝到protobuf根目录下，再把整个protobuf替换掉third_party下的protobuf就好了

再编译一下leveldb， 网上的教程有个问题，make完后libleveldb.a文件在 out-static目录下，这个注意一下就好了，还是把/usr/local下的  include和lib拷贝到leveldb下

这时可能会提示glog有问题，再编译一下glog就行了，glog编译也有问题，在git上glog的issue的52号问题有解答


弄好这些就可以了
