### ISSUE TITLE
sample编译错误，对‘vtable for phxpaxos::StateMachine’未定义的引用

### ISSUE THREAD

**Issue by liaobinxu** [tencent-wechat/phxpaxos#12]
cd phxpaxos/sample/phxecho;
make

`g++ -std=c++11 -I/data/tmp/phxpaxos -I/data/tmp/phxpaxos/third_party/protobuf/include/  -I/data/tmp/phxpaxos/third_party/leveldb/include/ -I/data/tmp/phxpaxos/third_party/glog/src/  -Wall -g -fPIC -m64  -Wno-unused-local-typedefs -I/data/tmp/phxpaxos/include -I/data/tmp/phxpaxos/plugin/include -I/data/tmp/phxpaxos/sample/phxecho -I/data/tmp/phxpaxos/third_party/leveldb/include/ -I/data/tmp/phxpaxos/third_party/protobuf/include/ -Wall -Werror  -c -o echo_sm.o echo_sm.cpp
g++ -std=c++11 -I/data/tmp/phxpaxos -I/data/tmp/phxpaxos/third_party/protobuf/include/  -I/data/tmp/phxpaxos/third_party/leveldb/include/ -I/data/tmp/phxpaxos/third_party/glog/src/  -Wall -g -fPIC -m64  -Wno-unused-local-typedefs -I/data/tmp/phxpaxos/include -I/data/tmp/phxpaxos/plugin/include -I/data/tmp/phxpaxos/sample/phxecho -I/data/tmp/phxpaxos/third_party/leveldb/include/ -I/data/tmp/phxpaxos/third_party/protobuf/include/ -Wall -Werror  -c -o echo_server.o echo_server.cpp
g++ -std=c++11 -I/data/tmp/phxpaxos -I/data/tmp/phxpaxos/third_party/protobuf/include/  -I/data/tmp/phxpaxos/third_party/leveldb/include/ -I/data/tmp/phxpaxos/third_party/glog/src/  -Wall -g -fPIC -m64  -Wno-unused-local-typedefs -I/data/tmp/phxpaxos/include -I/data/tmp/phxpaxos/plugin/include -I/data/tmp/phxpaxos/sample/phxecho -I/data/tmp/phxpaxos/third_party/leveldb/include/ -I/data/tmp/phxpaxos/third_party/protobuf/include/ -Wall -Werror  -c -o main.o main.cpp
g++ echo_sm.o echo_server.o main.o -o phxecho -L/data/tmp/phxpaxos/.lib -L/data/tmp/phxpaxos/third_party/protobuf/lib -L/data/tmp/phxpaxos/third_party/leveldb/lib/ -L/data/tmp/phxpaxos/third_party/glog/lib -L/data/tmp/phxpaxos/third_party/grpc/lib -L/data/tmp/phxpaxos/third_party/openssl/lib -g  /data/tmp/phxpaxos/lib/libphxpaxos_plugin.a /data/tmp/phxpaxos/lib/libphxpaxos.a /data/tmp/phxpaxos/third_party/leveldb/lib//libleveldb.a /data/tmp/phxpaxos/third_party/protobuf/lib/libprotobuf.a /data/tmp/phxpaxos/third_party/glog/lib/libglog.a /data/tmp/phxpaxos/third_party/glog/lib/libglog.a -lpthread
echo_sm.o：在函数‘phxpaxos::StateMachine::~StateMachine()’中：
/data/tmp/phxpaxos/include/phxpaxos/sm.h:61：对‘vtable for phxpaxos::StateMachine’未定义的引用
echo_sm.o：在函数‘phxpaxos::StateMachine::StateMachine()’中：
/data/tmp/phxpaxos/include/phxpaxos/sm.h:58：对‘vtable for phxpaxos::StateMachine’未定义的引用
echo_sm.o:(.data.rel.ro._ZTVN7phxecho9PhxEchoSME[_ZTVN7phxecho9PhxEchoSME]+0x30)：对‘phxpaxos::StateMachine::ExecuteForCheckpoint(int, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
echo_sm.o:(.data.rel.ro._ZTVN7phxecho9PhxEchoSME[_ZTVN7phxecho9PhxEchoSME]+0x38)：对‘phxpaxos::StateMachine::GetCheckpointInstanceID(int) const’未定义的引用
echo_sm.o:(.data.rel.ro._ZTVN7phxecho9PhxEchoSME[_ZTVN7phxecho9PhxEchoSME]+0x40)：对‘phxpaxos::StateMachine::LockCheckpointState()’未定义的引用
echo_sm.o:(.data.rel.ro._ZTVN7phxecho9PhxEchoSME[_ZTVN7phxecho9PhxEchoSME]+0x48)：对‘phxpaxos::StateMachine::GetCheckpointState(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’未定义的引用
echo_sm.o:(.data.rel.ro._ZTVN7phxecho9PhxEchoSME[_ZTVN7phxecho9PhxEchoSME]+0x50)：对‘phxpaxos::StateMachine::UnLockCheckpointState()’未定义的引用
echo_sm.o:(.data.rel.ro._ZTVN7phxecho9PhxEchoSME[_ZTVN7phxecho9PhxEchoSME]+0x58)：对‘phxpaxos::StateMachine::LoadCheckpointState(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned long)’未定义的引用
echo_sm.o:(.data.rel.ro._ZTIN7phxecho9PhxEchoSME[_ZTIN7phxecho9PhxEchoSME]+0x10)：对‘typeinfo for phxpaxos::StateMachine’未定义的引用
echo_server.o：在函数‘phxecho::PhxEchoServer::MakeLogStoragePath(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)’中：
/data/tmp/phxpaxos/sample/phxecho/echo_server.cpp:49：对‘phxpaxos::NodeInfo::GetPort() const’未定义的引用
/data/tmp/phxpaxos/sample/phxecho/echo_server.cpp:49：对‘phxpaxos::NodeInfo::GetIP[abi:cxx11]() const’未定义的引用
echo_server.o：在函数‘phxecho::PhxEchoServer::RunPaxos()’中：
/data/tmp/phxpaxos/sample/phxecho/echo_server.cpp:67：对‘phxpaxos::Options::Options()’未定义的引用
/data/tmp/phxpaxos/sample/phxecho/echo_server.cpp:82：对‘phxpaxos::GroupSMInfo::GroupSMInfo()’未定义的引用
/data/tmp/phxpaxos/sample/phxecho/echo_server.cpp:90：对‘phxpaxos::LoggerGoogle::GetLogger(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, void (*&)(int, char const*, __va_list_tag*))’未定义的引用
/data/tmp/phxpaxos/sample/phxecho/echo_server.cpp:100：对‘phxpaxos::Node::RunNode(phxpaxos::Options const&, phxpaxos::Node*&)’未定义的引用
echo_server.o：在函数‘phxecho::PhxEchoServer::Echo(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)’中：
/data/tmp/phxpaxos/sample/phxecho/echo_server.cpp:113：对‘phxpaxos::SMCtx::SMCtx()’未定义的引用
main.o：在函数‘parse_ipport(char const*, phxpaxos::NodeInfo&)’中：
/data/tmp/phxpaxos/sample/phxecho/main.cpp:45：对‘phxpaxos::NodeInfo::SetIPPort(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)’未定义的引用
main.o：在函数‘parse_ipport_list(char const*, std::vector<phxpaxos::NodeInfo, std::allocator<phxpaxos::NodeInfo> >&)’中：
/data/tmp/phxpaxos/sample/phxecho/main.cpp:64：对‘phxpaxos::NodeInfo::NodeInfo()’未定义的引用
main.o：在函数‘main’中：
/data/tmp/phxpaxos/sample/phxecho/main.cpp:92：对‘phxpaxos::NodeInfo::NodeInfo()’未定义的引用
/data/tmp/phxpaxos/sample/phxecho/main.cpp:113：对‘phxpaxos::NodeInfo::GetPort() const’未定义的引用
/data/tmp/phxpaxos/sample/phxecho/main.cpp:113：对‘phxpaxos::NodeInfo::GetIP[abi:cxx11]() const’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:36: recipe for target 'phxecho' failed
make: *** [phxecho] Error 1
`

**Comment by lynncui00** [comment]
请问g++是4.8及以上版本么吗？

**Comment by liaobinxu** [comment]
远远超过4.8了， 用的ubuntu 16.04编译的（gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609）
phxpaxos 除sample外其他都已经编译成功了
lib
├── extlib
│   ├── libphxkv_client.a
│   ├── libphxpaxos.a
│   └── libphxpaxos_plugin.a
├── libalgorithm.a
├── libcheckpoint.a
├── libcomm.a
├── libcommunicate.a
├── libcommunicate_tcp.a
├── libconfig.a
├── libinclude.a
├── liblogger_google.a
├── liblogstorage.a
├── libmaster.a
├── libmonitor.a
├── libnode.a
├── libphxkv_client.a
├── libphxpaxos.a
├── libphxpaxos_plugin.a
├── libsmbase.a
└── libutils.a

**Comment by lynncui00** [comment]
g++ echo_sm.o echo_server.o main.o -o phxecho -L/data/tmp/phxpaxos/.lib -L/data/tmp/phxpaxos/third_party/protobuf/lib -L/data/tmp/phxpaxos/third_party/leveldb/lib/ -L/data/tmp/phxpaxos/third_party/glog/lib -L/data/tmp/phxpaxos/third_party/grpc/lib -L/data/tmp/phxpaxos/third_party/openssl/lib -g /data/tmp/phxpaxos/lib/libphxpaxos_plugin.a /data/tmp/phxpaxos/lib/libphxpaxos.a /data/tmp/phxpaxos/third_party/leveldb/lib//libleveldb.a /data/tmp/phxpaxos/third_party/protobuf/lib/libprotobuf.a /data/tmp/phxpaxos/third_party/glog/lib/libglog.a /data/tmp/phxpaxos/third_party/glog/lib/libglog.a -lpthread

我拷贝你的命令替换路径后，在ubuntu的gcc (Ubuntu 5.2.1-22ubuntu2)上可以编译通过。目前看你的错误都是在链接静态库的时候找不到定义，具体原因还暂时未明。

**Comment by lynncui00** [comment]
@liaobinxu 试试在这个命令加入`-Wl,--no-as-needed`参数看能否编译成功。

**Comment by liaobinxu** [comment]
对所有 .a文件检查  no-as-needed ， 只提示没有main函数， 没有的错误
g++ -Wl,--no-as-needed  /data/tmp/phxpaxos/lib/libphxpaxos_plugin.a /data/tmp/phxpaxos/lib/libphxpaxos.a /data/tmp/phxpaxos/third_party/leveldb/lib//libleveldb.a /data/tmp/phxpaxos/third_party/protobuf/lib/libprotobuf.a /data/tmp/phxpaxos/third_party/glog/lib/libglog.a /data/tmp/phxpaxos/third_party/glog/lib/libglog.a
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o：在函数‘_start’中：
(.text+0x20)：对‘main’未定义的引用
collect2: error: ld returned 1 exit status

**Comment by lynncui00** [comment]
您好，我们编写了详细的编译手册在wiki里面，看看对你有无什么帮助，或者重新clone源码进行尝试？

**Comment by liaobinxu** [comment]
我在centos7上面编译成功了， 谢谢
