### ISSUE TITLE
protobuf 没有include目录

### ISSUE THREAD

**Issue by huchhong** [tencent-wechat/phxpaxos#13]
./autoinstall.sh 提示protobuf下没有include目录。

protobuf的代码是在phxpaxos根目录下用git submodule update --init --recursive获取的。下载的代码确实没有include目录。以前也没用过protobuf，是否新版本移除了include目录？

**Comment by liusifan** [comment]
1）请参考文档中关于 protobuf 编译的部分：https://github.com/tencent-wechat/phxpaxos/wiki/%E4%B8%AD%E6%96%87%E8%AF%A6%E7%BB%86%E7%BC%96%E8%AF%91%E6%89%8B%E5%86%8C
2）新增了一个 build.sh 文件，可以通过这个脚本一键编译；想了解具体的编译过程，可以查看这个脚本的具体内容。

**Comment by mariohuang** [comment]
刚下载的源代码是没有include目录的，可以使用./configure CXXFLAGS=-fPIC --prefix=当前目录，然后make && make install 将include目录编译出来，另外刚开始configure时可能会提示gmock不存在，如果遇到了可以去github.com/google下载。
