### ISSUE TITLE
文件句柄泄漏的问题

### ISSUE THREAD

**Issue by xinmingyao** [tencent-wechat/phxpaxos#15]
在使用kv后偶尔会出现文件句柄泄漏的问题，kv是在phxkv基础上改的，使用的是SSDB的数据引擎,从代码看SSDB引擎是对leveldb的简单包装。现象为kv数据库的某个leveldb的ldb文件被打开了1万多个句柄，导致应用crash了，正常情况下某个ldb文件只是被打开一次的。另外propose中有不少的404的错误（应该是超时吧？），这个一般是什么原因呢？
操作系统为ubuntu14.04,普通的sata硬盘，我们是单进程多线程模型，某个时刻只有一个线程会操作phxpaxos引擎。
下面为用lsof统计的进程句柄情况，只贴了部分泄漏句柄:
mcu     13810 server1 7176r   REG       8,1   1984229   2001190 /home/box/storage/kvdb/001125.ldb
mcu     13810 server1 7177r   REG       8,1   1984229   2001190 /home/box/storage/kvdb/001125.ldb
mcu     13810 server1 7178r   REG       8,1   1984229   2001190 /home/box/storage/kvdb/001125.ldb
mcu     13810 server1 7179r   REG       8,1   1984229   2001190 /home/box/storage/kvdb/001125.ldb
mcu     13810 server1 7180r   REG       8,1   1984229   2001190 /home/box/storage/kvdb/001125.ldb
mcu     13810 server1 7181r   REG       8,1   1984229   2001190 /home/box/storage/kvdb/001125.ldb
mcu     13810 server1 7182r   REG       8,1   1984229   2001190 /home/box/storage/kvdb/001125.ldb

**Comment by lynncui00** [comment]
PhxPaxos不会干涉任何状态机的实现，请仔细检查是否状态机实现本身有问题。

**Comment by xinmingyao** [comment]
用lsof -n查看进程的文件句柄，发现phxpaxos的日志文件句柄不断增加,多个线程会打开同一个日志文件,我这边只有一个phxpaxos的实例（有多个线程会调用）
server       19313 19363       root  mem       REG               8,10   2112539    1445938 //storage/paxoslog/g0/000021.ldb
server       19313 19363       root  mem       REG               8,10   2006067    1446290 //storage/paxoslog/g0/000026.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1446280 //storage/paxoslog/g0/000025.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1446278 //storage/paxoslog/g0/000024.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1446277 //storage/paxoslog/g0/000023.ldb
server       19313 19364       root  mem       REG               8,10  53747685    1446279 //storage/kvdb/000005.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1446274 //storage/paxoslog/g0/000022.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1445938 //storage/paxoslog/g0/000021.ldb
server       19313 19364       root  mem       REG               8,10   2006067    1446290 //storage/paxoslog/g0/000026.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1446280 //storage/paxoslog/g0/000025.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1446278 //storage/paxoslog/g0/000024.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1446277 //storage/paxoslog/g0/000023.ldb
server       19313 19605       root  mem       REG               8,10  53747685    1446279 //storage/kvdb/000005.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1446274 //storage/paxoslog/g0/000022.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1445938 //storage/paxoslog/g0/000021.ldb
server       19313 19605       root  mem       REG               8,10   2006067    1446290 //storage/paxoslog/g0/000026.ld

**Comment by xinmingyao** [comment]
麻烦看一下这个问题，一个晚上会有几百个句柄，(或者这个是正常的leveldb的特性？)下面是部分线程的打开的文件：
server       19313 19364       root  mem       REG               8,10   2488958    1449360/storage/paxoslog/g0/000034.ldb
server       19313 19364       root  mem       REG               8,10   2489082    1449358/storage/paxoslog/g0/000032.ldb
server       19313 19364       root  mem       REG               8,10   2488911    1449357/storage/paxoslog/g0/000030.ldb
server       19313 19364       root  mem       REG               8,10   2508496    1449355/storage/paxoslog/g0/000028.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1446280/storage/paxoslog/g0/000025.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1446278/storage/paxoslog/g0/000024.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1446277/storage/paxoslog/g0/000023.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1446274/storage/paxoslog/g0/000022.ldb
server       19313 19364       root  mem       REG               8,10   2112539    1445938/storage/paxoslog/g0/000021.ldb
server       19313 19364       root  mem       REG               8,10   2006067    1446290/storage/paxoslog/g0/000026.ldb
server       19313 19605       root  mem       REG               8,10   2488958    1449360/storage/paxoslog/g0/000034.ldb
server       19313 19605       root  mem       REG               8,10   2489082    1449358/storage/paxoslog/g0/000032.ldb
server       19313 19605       root  mem       REG               8,10   2488911    1449357/storage/paxoslog/g0/000030.ldb
server       19313 19605       root  mem       REG               8,10   2508496    1449355/storage/paxoslog/g0/000028.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1446280/storage/paxoslog/g0/000025.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1446278/storage/paxoslog/g0/000024.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1446277/storage/paxoslog/g0/000023.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1446274/storage/paxoslog/g0/000022.ldb
server       19313 19605       root  mem       REG               8,10   2112539    1445938/storage/paxoslog/g0/000021.ldb
server       19313 19605       root  mem       REG               8,10   2006067    1446290/storage/paxoslog/g0/000026.ldb

**Comment by lynncui00** [comment]
您好，leveldb里面一个ldb文件会被进程打开一次，并不会占用太多句柄。
lsof列出的多个线程并不代表每个线程占用了一个句柄，而是代表这些线程对这个文件有访问权限，实际上只要这个进程打开了这个文件，lsof都会列出所有子线程。

关于句柄泄漏的问题，还请检查状态机的实现。我们实际生产环境已经稳定运行了将近1年，没有出现句柄泄漏的问题。
