### ISSUE TITLE
测试phxecho时出现Could not create logging file: No such file or directory错误

### ISSUE THREAD

**Issue by FBono** [tencent-wechat/phxpaxos#16]
您好！我在编译安装完成phxpaxos之后尝试运行提供的phxecho示例，节点会弹出COULD NOT CREATE A LOGGINGFILE 20161019-015741.4175!Could not create logging file: No such file or directory错误，请问如何解决。
还有一个问题是输入的消息存放在log文件夹的哪个位置当中？

谢谢！

PS：第一个错误我们已经自行解决了（添加了一个log目录），但是仍然找不到相关的持久化存储文件。

**Comment by lynncui00** [comment]
会在运行的当前目录生成一个名字为logpath_ip_port的文件夹用于存放数据。

**Comment by FBono** [comment]
感谢回复，我打开logpath_ip_port文件夹，里面有三个.ldb文件和一个.log文件，打开是乱码，不能查看。
LOG和LOG.old文件能够打开，但是里面没有记录我输入过的值。还有一个vfile的文件夹，里面也没找到。
想问下这些数据具体是存放在哪个文件里面，如果是在.log或者.ldb文件里，应该如何打开查看，谢谢！

**Comment by FBono** [comment]
![default](https://cloud.githubusercontent.com/assets/17403086/19545291/a52ddc4c-96b7-11e6-9bb0-773080b8fa0a.PNG)
感谢回复，logpath_ip_port文件夹如图，里面有三个.ldb文件和一个.log文件，打开是乱码，不能查看。
LOG和LOG.old文件能够打开，但是里面没有记录我输入过的值。在vfile文件夹，里面也没找到。
想问下这些数据具体是存放在哪个文件里面，如果是在.log或者.ldb文件里，应该如何打开查看，谢谢！

**Comment by lynncui00** [comment]
这些是结构化的二进制文件，不是文本文件。就单纯使用phxpaxos来说，你是不用关心这些文件的格式的。
