### ISSUE TITLE
请教一下checkpoint的minchoseninstanceid的本意是什么？

### ISSUE THREAD

**Issue by weylan** [tencent-wechat/phxpaxos#20]
代码里面看，会延迟100个instance版本来设置 minchoseninstaneid.
但是这样导致启动的时候从存储的minchoseinstanceid里面重建checkpointmgr的时候无法找到对应的数据而导致失败。本意应该是 向前100个版本来存储minchoseninstanceid?

**Comment by lynncui00** [comment]
1. minchoseninstanceid是记录当前节点保留的最小的instance，以便决定是否要进行Checkpoint的拉取。同时也是重启后Cleaner的起始删除位置。
2. 延迟100个设置是为了减少写磁盘的次数。
3. 重启的时候会进行minchoseninstanceid的修复(FixMinChosenInstanceID)。
4. 不清楚你所说的失败是什么失败？是实际遇到的么？有无日志可以贴上来帮忙定位一下问题。

**Comment by weylan** [comment]
我设置了保存5个instance，运行到了cur_instance比如18,当前保存的instane 为13-18，
那么遇到的问题是重启之后Cleaner无法启动，查看日志，显示需要从版本0开始学习，但是13以前instance已经都被Delete掉了，min_instanceid由于有100个的版本延迟 一直没有存盘过。

**Comment by lynncui00** [comment]
Cleaner只会删除CheckpointInstanceID之前的Instance，如果删除到了18，那说明你给的CheckpointInstanceID是18。那么下次启动的时候必须同样给予18，否则违反了正确性，具体麻烦参考WIKI里面的状态机讲解。

**Comment by weylan** [comment]
我并没有使用自己状态机，而只是使用了选举功能 设置了保存版本数为5。我在看一下运行逻辑。

**Comment by lynncui00** [comment]
5这个值可能太小了，设置一个100以上的值试试。拉checkpoint是一个涉及到重启程序的繁重操作。一旦这个过程又落后了，就又陷入了拉checkpoint的循环。实际情况都是建议保留更多的log以避免拉checkpoint。
