### ISSUE TITLE
请问learner的实现原理是什么？

### ISSUE THREAD

**Issue by qidaneix** [tencent-wechat/phxpaxos#21]
看了关于phxpaxos的介绍文章和paxos协议的原理介绍，有几点疑惑：
1.一个paxos实例中的计算机节点是怎么确定一个值已经被选定的？proposer收到了过半的acceptor的accepted消息后确定的吗？
2.一个值已经在其他节点被确定的结果是通过learner获得（广播）的吗？比如说一个proposer收到过半acceptor的accepted消息后，形成确定性取值，实例编号加一，之后其他节点发现该节点已经进入下一实例，再用leaner获取该值，是这样吗？

**Comment by lynncui00** [comment]
1. 是的
2. 如果曾经进行过accpet操作，那么值已经存下来了，不需要再通过learn获得该值，如果没有accept，那么则需要通过learn获得该值。

**Comment by qidaneix** [comment]
对于第二个问题，是否存在这样一种情况：某个节点accept了某个取值，但是实际上这个取值并没有受到过半accept的认可（acceptor并不知道其他节点是否accept该值），也就是说这个值实际上未通过，而另一个值在这一次的paxos算法中形成了确定性取值，那这个节点用该值作为结果岂不出现问题？
谢谢！

**Comment by lynncui00** [comment]
这个会根据ballot来判断这个值是否被确定的值。

**Comment by qidaneix** [comment]
ballot值是何意义，acceptor如何获取？可以解释一下吗？

**Comment by lynncui00** [comment]
请仔细阅读WIKI里面的Paxos理论介绍。
