### ISSUE TITLE
Learner运行的时候直接exit了。我看了一下代码，请教一下exit了下一步怎么办呢？重启么？

### ISSUE THREAD

**Issue by weylan** [tencent-wechat/phxpaxos#22]
int Learner :: OnSendCheckpoint_End(const CheckpointMsg & oCheckpointMsg)
{
    //.......
    BP->GetCheckpointBP()->ReceiveCheckpointAndLoadSucc();
    PLGImp("All sm load state ok, start to exit process");
    exit(-1);
     return 0;
}

这个地方直接exit 进程了。成功之后难道不是应该恢复sm么？为什么直接退出进程而非线程。
我发现重启可以恢复，但是为什么一定要重启呢？是不是有更优雅的办法？

**Comment by lynncui00** [comment]
因为获得新的状态机Checkpoint之后，开发者需要以这些新的状态机Checkpoint文件来进行状态机的重新加载。重启是为了简化开发者的开发难度，如果采取软启动，那么在这个多线程的环境下，开发者对状态机进行重新加载，是一件非常复杂的事情。
并且我们再次强调，拉取Checkpoint是一个非常重的操作，保留更多的Paxoslog以规避这个操作。

**Comment by weylan** [comment]
好的，清楚了。
只是我暂时只用到选举功能，而且是单线程环境(phxpaxos自己维护的不计的话)，希望能够定制这些操作。而且直接exit会导致库里面多线程一些析构顺序异常，因为我本来是单线程，但是在phxpaxos线程直接exit会导致多线程析构处理，和我原有单线程设置冲突了，希望能够我自己来调用exit函数。

**Comment by lynncui00** [comment]
这个函数是运行在PhxPaxos的线程，如果由你来处理Exit的话，Exit函数仍然是运行在PhxPaxos的线程，那么你还是避免不了要处理跨线程回收的问题。

我们会考虑如何优雅的解决这个问题，但还是要考虑不带来更多的开发难度，谢谢你的建议。

如果仅仅使用选举功能，保留10W条PaxosLog，假如续租间隔是5秒，那么只有当一个机器落后了138天的数据，才会触发拉取Checkpoint的操作，正因为这个是低频事件，所以我们暂未花过多精力去优化这一块。

**Comment by weylan** [comment]
我现在续租间隔10s 保存1200条两个小时的log。由于我使用自己的数据库和网络（下一步打算深入使用
phxpaxos）所以10W条记录比较吃力。我会再考虑一下您的建议，加大log的存储。

暂时其实问题不大，只是上线之前需要进行各方面的测试，宕机有概率会导致数据写回的一些混乱，可能和库的适配有关系，从而paxos状态机无法恢复，但是我暂时只是使用选举，所以直接清除所有数据从头学习即可，问题不大。谢谢。

**Comment by lynncui00** [comment]
> 宕机有概率会导致数据写回的一些混乱，可能和库的适配有关系，从而paxos状态机无法恢复
这个不符合我们测试的预期，我们之前多次测试过这种情况，并不会出现问题。我们在进行测试看看，另外能否提供一些无法恢复的错误日志供我们定位问题？

**Comment by lynncui00** [comment]
经过我们再度测试，发现在HoldPaxosLogCount设置小于50的时候，会陷入拉Checkpoint的死循环，会不断重启，不知你遇到的是否是这个问题。我们很快会发布下一个版本，到时候会对这个HoldPaxosLogCount做保护。

**Comment by weylan** [comment]
没有 我设置的为1200。另外我是希望能够打一个退出标记由我的线程来执行exit。

**Comment by weylan** [comment]
另外 等我下次遇到混乱的时候再提供日志吧，暂时没有重现出来。而且有可能是宕机和我自己的存储逻辑处理不全导致的问题。

**Comment by lynncui00** [comment]
通过CheckpointBP来延缓Exit是OK的。

**Comment by weylan** [comment]
又遇到了无法启动的问题，现象就是尝试获取一个极其新的instanceid 138262，而系统最大的instanceid只有137307。暂时没有分析清楚问什么会出现这种情况，core的问题已经修复了，也没有存盘失败的记录。

PN8phxpaxos8InstanceE::Init Acceptor.OK, Log.InstanceID 137307 Checkpoint.InstanceID 138262


err : [45;37m Showy: PN8phxpaxos5PNodeE::InitLogStorage OK, use user logstorage [0m
err : [45;37m Showy: PN8phxpaxos5PNodeE::InitNetWork OK, use user network [0m
crit : [44;37m Imp(0): PN8phxpaxos18MasterStateMachineE::Init OK, master nodeid 7 version 138261 expiretime 3722449268 [0m
err : [45;37m Showy(0): PN8phxpaxos11MasterDamonE::TryBeMaster Ohter as master, can't try be master, masterid 7 myid 6 [0m
err : [45;37m Showy(0): PN8phxpaxos20SystemVariablesStoreE::Read DB.Get not found, groupidx 0 [0m
err : [45;37m Showy(0): PN8phxpaxos9SystemVSME::Init variables not exist [0m
crit : [44;37m Imp(0): PN8phxpaxos9SystemVSME::RefleshNodeID ip 0.0.0.0 port 6 nodeid 6 [0m
err : [45;37m Showy(0): PN8phxpaxos11MasterDamonE::run TryBeMaster, sleep time 4305ms [0mcrit : [44;37m Imp(0): PN8phxpaxos9SystemVSME::RefleshNodeID ip 0.0.0.0 port 7 nodeid 7 [0m
crit : [44;37m Imp(0): PN8phxpaxos9SystemVSME::RefleshNodeID ip 0.0.0.0 port 9 nodeid 9 [0m
crit : [44;37m Imp(0): PN8phxpaxos6ConfigE::Init OK [0m
err : [45;37m Showy(0): PN8phxpaxos8PaxosLogE::GetMaxInstanceIDFromLog OK, MaxInstanceID 137307 groupidsx 0 [0m
err : [45;37m Showy(0): PN8phxpaxos13AcceptorStateE::Load GroupIdx 0 InstanceID 137307 PromiseID 270 PromiseNodeID 7 AccectpedID 270 AcceptedNodeID 7 ValueLen 20 Checksum 1663223060 [0m
err : [45;37m Showy(0): PN8phxpaxos8AcceptorE::Init OK [0m
err : [45;37m Showy(0): PN8phxpaxos7CleanerE::FixMinChosenInstanceID ok, old minchosen 136311 fix minchosen 136311 [0m
err : [45;37m Showy(0): PN8phxpaxos8InstanceE::Init Acceptor.OK, Log.InstanceID 137307 Checkpoint.InstanceID 138262 [0m
err : [45;37m Showy(0): PN8phxpaxos8InstanceE::Init NowInstanceID 138262 [0m
info : PaxosDB::Get not found:iGroupIdx=0:llInstanceID=138261:value=997:data=50661
alert : [41;37m ERR(0): PN8phxpaxos8PaxosLogE::ReadState DB.Get fail, groupidx 0 ret -2 [0m
info : RunPaxos:zones=6;7;9:ret=-2:m_poPaxosNode=0
info : RunPaxos:g_zoneid=6:g_center=2:g_election_center=6;7;9
err : [45;37m Showy: PN8phxpaxos5PNodeE::InitLogStorage OK, use user logstorage [0m
err : [45;37m Showy: PN8phxpaxos5PNodeE::InitNetWork OK, use user network [0m
crit : [44;37m Imp(0): PN8phxpaxos18MasterStateMachineE::Init OK, master nodeid 7 version 138261 expiretime 3722450266 [0m
err : [45;37m Showy(0): PN8phxpaxos11MasterDamonE::TryBeMaster Ohter as master, can't try be master, masterid 7 myid 6 [0m
err : [45;37m Showy(0): PN8phxpaxos11MasterDamonE::run TryBeMaster, sleep time 3871ms [0m
err : [45;37m Showy(0): PN8phxpaxos20SystemVariablesStoreE::Read DB.Get not found, groupidx 0 [0m
err : [45;37m Showy(0): PN8phxpaxos9SystemVSME::Init variables not exist [0m
crit : [44;37m Imp(0): PN8phxpaxos9SystemVSME::RefleshNodeID ip 0.0.0.0 port 6 nodeid 6 [0m
crit : [44;37m Imp(0): PN8phxpaxos9SystemVSME::RefleshNodeID ip 0.0.0.0 port 7 nodeid 7 [0m
crit : [44;37m Imp(0): PN8phxpaxos9SystemVSME::RefleshNodeID ip 0.0.0.0 port 9 nodeid 9 [0m
crit : [44;37m Imp(0): PN8phxpaxos6ConfigE::Init OK [0m
err : [45;37m Showy(0): PN8phxpaxos8PaxosLogE::GetMaxInstanceIDFromLog OK, MaxInstanceID 137307 groupidsx 0 [0m
err : [45;37m Showy(0): PN8phxpaxos13AcceptorStateE::Load GroupIdx 0 InstanceID 137307 PromiseID 270 PromiseNodeID 7 AccectpedID 270 AcceptedNodeID 7 ValueLen 20 Checksum 1663223060 [0m
err : [45;37m Showy(0): PN8phxpaxos8AcceptorE::Init OK [0m
err : [45;37m Showy(0): PN8phxpaxos7CleanerE::FixMinChosenInstanceID ok, old minchosen 136311 fix minchosen 136311 [0m
err : [45;37m Showy(0): PN8phxpaxos8InstanceE::Init Acceptor.OK, Log.InstanceID 137307 Checkpoint.InstanceID 138262 [0m
err : [45;37m Showy(0): PN8phxpaxos8InstanceE::Init NowInstanceID 138262 [0m
info : PaxosDB::Get not found:iGroupIdx=0:llInstanceID=138261:value=997:data=50661
alert : [41;37m ERR(0): PN8phxpaxos8PaxosLogE::ReadState DB.Get fail, groupidx 0 ret -2 [0m
info : RunPaxos:zones=6;7;9:ret=-2:m_poPaxosNode=0
info : RunPaxos:g_zoneid=6:g_center=2:g_election_center=6;7;9
crit : [44;37m Imp: PN8phxpaxos7NetWorkE::OnReceiveMessage receive msglen 26 [0m

**Comment by lynncui00** [comment]
你使用了自己自定义的LogStorage模块，这里对这个使用做一下说明。
1. 获取数据不存在要求返回码为1，从日志看你返回了-2，从而导致启动不了。
2. ClearAllLog函数只允许并要求清除掉所有PaxosLog，但不能清除SystemVariables和MasterVariables。
3. 对于oWriteOptions.bSync设置为True时，必须以fdatasync强制刷盘，否则当机器重启导致丢失部分磁盘数据的时候，有极小的几率会导致数据不一致。

注：尝试获取一个极新的Instance是正常现象，因为MasterVariables会时刻对齐，参考leaner.cpp:OnSendNowInstanceID函数，Master的Checkpoint会领先于PaxosLog的位置，当这时候发生了重启，就会出现这种现象。你按1的要求设置好返回值后，就可以启动成功了。

对于模块的自定义使用方面目前文档还不是很完善，我们会尽快补充。

**Comment by weylan** [comment]
好的，确实是，如果是空数据返回了1，如果是超出范围的返回了-2，我修改一下。
