### ISSUE TITLE
文字错误

### ISSUE THREAD

**Issue by xinmingyao** [tencent-wechat/phxpaxos#24]
https://github.com/tencent-wechat/phxpaxos/wiki/options.h%E5%8F%82%E6%95%B0%E4%B8%AD%E6%96%87%E8%AF%B4%E6%98%8E 中
bUserBatchPropose 应该为 bUseBatchPropose

readme中 --recursive-submodules应该为 --recurse-submodules

**Comment by lynncui00** [comment]
谢谢勘误，已经fix。
