### ISSUE TITLE
主master内存问题

### ISSUE THREAD

**Issue by xinmingyao** [tencent-wechat/phxpaxos#25]
主master测试过程中内存会增长，是否是缓存原因？缓存最大会到多大？

**Comment by lynncui00** [comment]
这个视乎你的请求value有多大，以及开启了多少个group而定。除了leveldb自身的固定内存占用（一个group几M的规模），在网络层以及磁盘IO会为value分配一个固定缓冲区，这个缓冲区是随着请求的value大小自动撑大的，如果都是小value请求比如几百k的规模，phxpaxos应该不会占用太多内存。

本身phxpaxos没有缓存，不清楚你指的缓存是啥意思。
这个实际内存会增长到多大，你可以具体通过不断输入请求来进行测试。
