### ISSUE TITLE
Multi-Paxos提交的问题

### ISSUE THREAD

**Issue by taozhijiang** [tencent-wechat/phxpaxos#27]
Cui，你好

看到你们在知乎专栏的教程，十分感谢。在此我想问一个问题：

我想问下，对于执行失败的command会留下gap，这些gap会用no-op操作进行填充，那么原先这些失败的命令怎么办？客户端请求返回错误然后让客户端重试么？
另外，我看好像Multi-Paxos对提交的顺序是没有保证的，Multi-Paxos对预取的r个命令可以任意的顺序Chosen Value，而且Leader失败后新的Leader对未决的命令也是任意顺序执行的，就是其假定r个命令之间Chosen Value是没有因果或者依赖关系的，是不是这样？如果这样会不会对某些业务有影响？还是强制序列化操作？

**Comment by taozhijiang** [comment]
还有一个：https://zhuanlan.zhihu.com/p/21466932?refer=lynncui
这里预取的多个instance，他们的编号都是1，这个编号是不是提案编号，提案编号应该不仅仅instance中唯一，而是在所有的instance都是唯一的吧？还是你只是想说明问题，表达提案号因为其他Proposer需要提交而被迫升高和没有升高的因素？

我对Paxos刚刚了解，所以烦请能够帮忙解惑一下，多谢！

**Comment by lynncui00** [comment]
您好，你的问题表述不是很清晰，我大致说明一下吧，但不针对具体问题。

1. 关于no-op填充这个不是必要的。如果进行了填充，那么客户端在填充之前就已经知道失败了，客户选择重试也是以新的instance进行，所以这里没有什么问题。

2. 论文里面提到的多个instance并行提交我们的phxpaxos并未实现，因为我们觉得这个收效不大，并且带来更多复杂问题，比如no-op填充问题。

3. 关于预取多个instance并行提交，这里也顺便解释一下。假设instance i之前的所有instance都已经选出chosen value以及进行状态机转移了，那么我们可以选取[i, i+a)这个窗口作为新的提交窗口，在这个窗口内，我们可以任意选取instance进行command的提交，但是，状态机的执行仍然是串行的，这也就导致了必须等待之前的所有instance选出chosen value并进行了状态转移，才能进行请求返回。举个例子，a=10， 当i+9这个instance选出了chosen value，但i+7仍然未选出，那么i+9这个instance对应的command请求必须block住等待i+7，如果i+7执行失败了，则仍然需要填充no-op，才能使得i+9可以返回。所以他本质上还是串行的。我们phxpaxos的实现，采取了另外的做法，我们先预先等待a个请求，然后a个请求合并成一个command进行提交，这样获得的效果与并行提交效果差距不大，并且更为可控。

4. https://zhuanlan.zhihu.com/p/21466932?refer=lynncui 里面提到的优化，instance是串行推进的，不存在多个instance同时执行paxos算法，而正是因为这个优化，才使得提案编号变成了全局编号。

**Comment by taozhijiang** [comment]
哈哈，没想到这么快就得到回复了。

no-op填充的确不是必须的，Paxos可以选择后面的命令来占用这个instance number，如果你说失败返回给客户端让客户端决定重试还是放弃，那么这里也就说的通了。
还有就是我可能把Chosen Value和Commit弄混了，按照你的意思也就是Chosen Value可以在预取的窗口中并行执行，而且结果以任意顺序出来，但是commit使得状态机转移必须是严格串行化的。
查看Paxos made code中，应该就是Chosen Value可以以任意顺序得出抉择，但是replics执行callback是严格序列化的，而通常真正变更和执行也是体现在callback中的。

关于知乎专栏里面的，还是没明白提案编号是单个instance内部唯一的，还是所有instances全局唯一的？因为Instance 1,2,3,4... 里面的1(A)出现了好多次

**Comment by lynncui00** [comment]
提案编号是单个instance内部唯一的，但是由于Promise[i, 无穷大)的优化，迫使这个提案编号在全局内是单调递增的。所以连续的1(A)是合理的。

**Comment by taozhijiang** [comment]
好的。主要是我还没来得及看代码，所以很多东西都还不了解

多谢你的回复
