### ISSUE TITLE
checkpoint id 和 instanceid 不一致导致的问题

### ISSUE THREAD

**Issue by xinmingyao** [tencent-wechat/phxpaxos#33]
一台机器上的checkpoint id比 instanceid更大（目前原因不是很清楚，使用paxos_tools获得的这台机器的最大instanceid 为6986455，理论上应该也会存在这种情况，因为checkpoint id和instanceid是独立写入的）

016-11-24 17:06:43.11s CheckpointInstanceID 7030709
2016-11-24 17:06:43.11s ^[[41;37m ERR(0): PN8phxpaxos8DatabaseE::GetMinChosenInstanceID no min chosen instanceid ^[[0m
2016-11-24 17:06:43.11s ^[[41;37m ERR(0): PN8phxpaxos8InstanceE::InitLastCheckSum las checksum not exist, now instanceid 7030710 ^[[0m

另外的一台机器加入集群，但是他的instanceid < 7030710,所以会请求同步数据，但是实际上6986455到7030709是没有数据的，这样会导致同步失败,主master会有日志
RR(0): PN8phxpaxos13LearnerSenderE::SendLearnedValue SendOne fail, SendInstanceID 6986456 SendToNodeID 9402119685132001185 ret 1）
这台机器一直加入不了集群，而且这时候 GetMaster的返回的值是不确定的，有时候是正确的master ip和port，有时候是0.0.0.0和 0

**Comment by lynncui00** [comment]
checkpoint id比 instanceid更大，有三种情况。
1. checkpoint id出错了。
2. paxos log丢了末尾一段数据。
3. 从别的机器拉回来的checkpoint。

从你的情况来看，其他机器向这台机器请求同步数据，说明肯定是1这种情况。
checkpoint id和instance id虽然是独立写入，但是checkpoint id必须是比instance id小的，不可能无端端构造出来一个更大的instance id。
出现这种情况整个系统肯定就无法工作了。

**Comment by xinmingyao** [comment]
checkpoint id比 instanceid更大的数据是实时从一台正在运行的机器上拷贝过来的，估计还是磁盘sync的问题，暂时也没想到好的办法，只能先写个工具处理一下

**Comment by lynncui00** [comment]
不能自己人肉单独拷贝状态机数据，这样会有很多状态不对的。
稳妥的做法应当是把停机，然后将状态机数据+paxos log数据一起拷贝过来。

**Comment by lynncui00** [comment]
@xinmingyao 您好，刚提交了一个代码，增加了针对你这种情况的Init检查，对于你这种情况会报启动失败，使得你可以更快的发现问题。

相关代码在`src/algorithm/instance.cpp ProtectionLogic_IsCheckpointInstanceIDCorrect`函数。
