### ISSUE TITLE
为什么对BallotNumber的对比是>=，不是应该只有>才算是合法的提议id吗？

### ISSUE THREAD

**Issue by willkozheng** [tencent-wechat/phxpaxos#34]
看acceptor的实现，和理解有些不同，请指教，谢谢。

    if (oBallot >= m_oAcceptorState.GetPromiseBallot())
    {

    bool operator >= (const BallotNumber & other) const
    {
        if (m_llProposalID == other.m_llProposalID)
        {
            return m_llNodeID >= other.m_llNodeID;
        }
        else
        {
            return m_llProposalID >= other.m_llProposalID;
        }
    }

**Comment by lynncui00** [comment]
而b>=pb是工程实现上的考虑。
首先，在分布式的异步网络中，出现相同的(b,v)是很正常的，注意相同的(b,v)是不违背Paxos约束条件第一点的。只有相同的b，但不同的v才会违背。
其次，在工程上，因为网络通信而非Reject导致协议的进展性问题，盲目的提升b进行重试也是有问题的，具体什么问题这里就不展开了。而不提升b进行重试也会出现相同的(b,v)。
所以在工程上是必须处理b>=pb的情况的。

**Comment by willkozheng** [comment]
谢谢。既然b>=pb不违背，我总结下工程实现用>=不用>的理解。

如果失败重试递增b，b的资源消耗会加快，也可能引起活锁（phxpaxos accpet拒绝会sleep 30ms），活锁加剧资源的消耗，最终引起，b达到上限，缺乏有效可用的b，导致集群停止工作。

而用>=的话，前提条件是 不同的proposers不会生成相同的b。phxpaxos用nodeid(ip+port) + seq no作为b，理论上node id不错乱，这个前提条件可以符合。

prepare阶段失败只要不是被accptor明确拒绝，都会复用相同b。

**Comment by lynncui00** [comment]
@willkozheng 对的。
