### ISSUE TITLE
PhxPaxos是否强制了Master/Follower机制

### ISSUE THREAD

**Issue by thisisbaozi** [tencent-wechat/phxpaxos#36]
我在阅读代码时候发现，如果当前Group对应的Instance为Follower，则会skip对应proposed的value，详细见代码:

``void Instance :: CheckNewValue()
{
if (m_poConfig->IsIMFollower())
{
  PLGErr("I'm follower, skip this new value");
  m_oCommitCtx.SetResultOnlyRet(PaxosTryCommitRet_Follower_Cannot_Commit);
  return ;
}
}`

我的疑问是PhPaxos是否可以取消这个限制，或者改为配置，比如我们的应用是希望支持多点写入的，只是说，我们的client会去基于一个简单的机制去选择一个非严格意义上的master（优先写入节点，减少冲突），但是其它的节点也是可以写入的（在出现membership change的时候）。

**Comment by lynncui00** [comment]
Follower是一个特殊的不参与投票的节点，不属于Paxos的范畴，默认是没有Follower的，所以任何节点都可以调用Propose。

下面解释一下Follower：
Paxos每次写入都需要同步数据到至少多数派，如果某些业务需要大量的节点用于读的话，那么写入的同步开销会比较大，这时候我们提供了一种Follower机制。比如我们设置Paxos集群为5个节点，另外附加10个Follower，这些Follower可以自动从5个节点的集群拉取paxos log数据并进行状态机输入，但是不参与任何的paxos投票。
这些Follower节点可以用来提供非latest的读，但不能写。

默认是没有Follower的，如需使用，可通过options进行配置。

另外为了减少写入冲突，我们提供了Master机制，但这个完全是由开发者自行通过GetMaster控制的，Propose函数进行写入限制。
