### ISSUE TITLE
第三方库问题

### ISSUE THREAD

**Issue by lemon0910** [tencent-wechat/phxpaxos#40]
为什么不直接将使用到的第三方库直接放到third_party目录下，而需要去下载，这样可能会因为第三方库的版本更新导致编译问题，而且管理起来也不太方便

**Comment by buptmiao** [comment]
不是有  .gitmodules吗，git submodule update --init 就安装好指定版本了。

**Comment by lemon0910** [comment]
恩，只是感觉麻烦点
