### ISSUE TITLE
重启时状态机恢复问题

### ISSUE THREAD

**Issue by lmdyyh** [tencent-wechat/phxpaxos#42]
如果一个节点在重启时，Instance初始化时，相关代码
uint64_t llCPInstanceID = m_oCheckpointMgr.GetCheckpointInstanceID() + 1;  

    uint64_t llNowInstanceID = llCPInstanceID;
    if (llNowInstanceID < m_oAcceptor.GetInstanceID())
    {
        ret = PlayLog(llNowInstanceID, m_oAcceptor.GetInstanceID());  
        if (ret != 0)
        {
            return ret;
        }

        PLGImp("PlayLog OK, begin instanceid %lu end instanceid %lu", llNowInstanceID, m_oAcceptor.GetInstanceID());

        llNowInstanceID = m_oAcceptor.GetInstanceID();
    }
    else
    {
        if (llNowInstanceID > m_oAcceptor.GetInstanceID())
        {
            ret = ProtectionLogic_IsCheckpointInstanceIDCorrect(llNowInstanceID, m_oAcceptor.GetInstanceID());
            if (ret != 0)
            {
                return ret;
            }
            m_oAcceptor.InitForNewPaxosInstance();
        }
        
        m_oAcceptor.SetInstanceID(llNowInstanceID);
    }
在if分支中会将llNowInstanceID到m_oAcceptor.GetInstanceID()的日志对状态机进行重放，从而恢复状态机。我的理解是，这里恢复应该是首先加载llNowInstanceID－1，即此CheckpointInstanceID时落盘的数据，然后重放llNowInstanceID到m_oAcceptor.GetInstanceID()的日志才能恢复所有的数据。

**Comment by lynncui00** [comment]
状态机在调用Node::RunNode之前要先把状态机的数据准备好，[0,CheckpointInstanceID]的数据Paxos会认为状态机已经自己加载好了，不再需要重放。
在WIKI里面有对状态机以及Checkpoint的详细说明。

**Comment by lmdyyh** [comment]
学习了WIKI相关说明。
Checkpoint功能应该是redis的rdb和zk的snapshot功能类似，用于恢复内存状态机。phxpaxos对Checkpoint功能的设计是由用户控制是否打开此功能，所以对于Checkpoint的使用逻辑在机器重启时需要业务逻辑自身去控制。
算法本身是在Learner学习时，如果本机落后的很多，才会向集群中其他节点请求Checkpoint文件，使用Checkpoint功能（开关打开前提下）。

**Comment by lynncui00** [comment]
Checkpoint是默认必须存在的内容，不是由用户控制打开的。
用户控制打开的是是否由paxos协助生成Checkpoint。

**Comment by lmdyyh** [comment]
1）用户通过bUseCheckpointReplayer控制是否由paxos协助生成Checkpoint，如果打开开关，需要重载方法
bool StateMachine :: ExecuteForCheckpoint(const int iGroupIdx, const uint64_t llInstanceID, 
        const std::string & sPaxosValue)
2）节点如果只能通过请求Checkpoint来恢复状态机时，会发送MsgType_PaxosLearner_AskforCheckpoint类型请求，节点收到请求后，在CheckpointSender :: SendCheckpoint()中发送所需文件，其中：
    int ret = m_poLearner->SendCheckpointBegin(
            m_iSendNodeID, m_llUUID, m_llSequence, 
            m_poSMFac->GetCheckpointInstanceID(m_poConfig->GetMyGroupIdx()));
    if (ret != 0)
    {
        PLGErr("SendCheckpointBegin fail, ret %d", ret);
        return;
    }

    ret = m_poLearner->SendCheckpointBegin(
            m_iSendNodeID, m_llUUID, m_llSequence, 
            m_poSMFac->GetCheckpointInstanceID(m_poConfig->GetMyGroupIdx()));
    if (ret != 0)
    {
        PLGErr("SendCheckpointBegin fail, ret %d", ret);
        return;
    }
请问调用2次SendCheckpointBegin是出于什么考量？

**Comment by lynncui00** [comment]
这个没有算法上的特殊含义，是一些工程上的考虑。
由于网络收发包是全异步的，是否成功收发是不知道的。
而拉取Checkpoint的机器往往是新启动的或者重启的，那么假如B向A拉取Checkpoint，那么意味着A到B的tcp发送通道需要重新建立，而SendCheckpointBegin是这个A->B通道的第一个TCP网络包，实际中会经常因为旧的发送通道未能正常关闭而错误写入到旧通道，导致第一个网络包丢失。

**Comment by lmdyyh** [comment]
请求节点收到SendCheckpointBegin后，会删除临时文件和日志文件。如果两个SendCheckpointBegin包到达节点的这段时间内，节点已经开始接收到Checkpoint的数据，这个时候第二个SendCheckpointBegin把正在使用的临时文件和日志文件删除了，导致正在进行的同步操作失败，客户端返回了CheckpointSendFileAckFlag_Fail，这样节点应该就加入不了集群了。

**Comment by lynncui00** [comment]
发送通道使用的是单TCP连接，所以一般不会出现发送乱序，除非频繁断线重连的极少数异常情况。这种情况也有超时重来的机制。

**Comment by lmdyyh** [comment]
感谢耐心解答！！！
