### ISSUE TITLE
Prepare和Accept阶段持久化问题

### ISSUE THREAD

**Issue by lmdyyh** [tencent-wechat/phxpaxos#44]
Acceptor中OnPrepare和OnAccept中都调用Persist来持久化AcceptorState，存储是通过键llInstanceID从leveldb中拿到sFileID从而定位到值在文件中的偏移量。
由于leveldb中两次键都是一样，leveldb中会保存OnAccept中的sFileID，所以读的时候能够读到选定的值。在日志文件中，使用的是追加写，OnPrepare和OnAccept在文件中写了两条关于llInstanceID的日志，如果上面解读的正确，那么请问OnPrepare保存的日志是什么作用？

**Comment by lynncui00** [comment]
Prepare阶段必须持久化Promise的ballot，这个是算法要求的。

**Comment by lmdyyh** [comment]
感谢解答！
