### ISSUE TITLE
libphxpaxos.a编译失败，但在phxpaxos/.lib/目录下已生成libphxpaxos.a

### ISSUE THREAD

**Issue by xufangqing** [tencent-wechat/phxpaxos#47]
1. 

所有依赖protobuf和leveldb均已经编译并安装OK，版本如下：
commit 1b964f747e77ad23cd534a7d6c09e72d466c81e2
Author: lynncui00 <lynncui00@gmail.com>
Date:   Fri Jan 6 17:15:08 2017 +0800

2. 

编译错误如下所示，其中依赖的头文件均存在
_g++ -std=c++11 -O2 -I/zwork/git/phxpaxos -I/zwork/git/phxpaxos/third_party/protobuf/include/  -I/zwork/git/phxpaxos/third_party/leveldb/include/ -I/zwork/git/phxpaxos/third_party/glog/src/  -Wall -fPIC -m64  -Wno-unused-local-typedefs -I/zwork/git/phxpaxos/src/utils -Wall -Werror -I/zwork/git/phxpaxos/src/utils -Wall -Werror  -c -o wait_lock.o wait_lock.cpp
In file included from /zwork/git/phxpaxos/src/logstorage/db.h:29:0,
                 from /zwork/git/phxpaxos/src/node/pnode.h:27,
                 from /zwork/git/phxpaxos/src/node/pnode.cpp:22:
/zwork/git/phxpaxos/src/comm/comm_include.h:24:28: fatal error: ./paxos_msg.pb.h: No such file or directory
 #include "./paxos_msg.pb.h"
                            ^
compilation terminated.
In file included from /zwork/git/phxpaxos/src/logstorage/db.h:29:0,
                 from /zwork/git/phxpaxos/src/node/pnode.h:27,
                 from /zwork/git/phxpaxos/src/node/node.cpp:23:
/zwork/git/phxpaxos/src/comm/comm_include.h:24:28: fatal error: ./paxos_msg.pb.h: No such file or directory
 #include "./paxos_msg.pb.h"
                            ^
compilation terminated.
ori_make: *** [/zwork/git/phxpaxos/src/node/node.o] Error 1
ori_make: *** Waiting for unfinished jobs....
ori_make: *** [/zwork/git/phxpaxos/src/node/pnode.o] Error 1
In file included from /zwork/git/phxpaxos/src/communicate/tcp/message_event.h:28:0,
                 from /zwork/git/phxpaxos/src/communicate/tcp/tcp_acceptor.h:26,
                 from /zwork/git/phxpaxos/src/communicate/tcp/tcp.h:25,
                 from /zwork/git/phxpaxos/src/communicate/dfnetwork.h:26,
                 from /zwork/git/phxpaxos/src/communicate/udp.cpp:31:
/zwork/git/phxpaxos/src/comm/comm_include.h:24:28: fatal error: ./paxos_msg.pb.h: No such file or directory
 #include "./paxos_msg.pb.h"
                            ^
In file included from /zwork/git/phxpaxos/src/communicate/tcp/message_event.h:28:0,
                 from /zwork/git/phxpaxos/src/communicate/tcp/tcp_acceptor.h:26,
                 from /zwork/git/phxpaxos/src/communicate/tcp/tcp.h:25,
                 from /zwork/git/phxpaxos/src/communicate/dfnetwork.h:26,
                 from /zwork/git/phxpaxos/src/communicate/dfnetwork.cpp:22:
/zwork/git/phxpaxos/src/comm/comm_include.h:24:28: fatal error: ./paxos_msg.pb.h: No such file or directory
 #include "./paxos_msg.pb.h"_

3.

感觉makefile的依赖不对，尤其对于$(SRC_BASE_PATH)/.lib/libphxpaxos.a $(SRC_BASE_PATH)/.lib/extlib/libphxpaxos.a这两个库有什么区别不明白。其中 $(SRC_BASE_PATH)/.lib/libphxpaxos.a的依赖$(PHXPAXOS_SRC)为空，我的makefile通过./autoinstall.sh生成，生成的makefile如下：
_lib_phxpaxos: phxpaxos_dir $(SRC_BASE_PATH)/.lib/libphxpaxos.a $(SRC_BASE_PATH)/.lib/extlib/libphxpaxos.a

phxpaxos_dir:$(PHXPAXOS_FULL_LIB_PATH)
	@for dir in $^;\
	do \
	current_dir=`readlink $$dir -m`;\
	pwd_dir=`pwd`;\
	pwd_dir=`readlink $$pwd_dir -m`;\
	if ([ "$$current_dir" != "$$pwd_dir" ]); then \
	make -C $$dir;\
	fi;\
	done

$(SRC_BASE_PATH)/.lib/libphxpaxos.a: $(PHXPAXOS_SRC)
	ar -cvq $@ $(PHXPAXOS_SRC)

PHXPAXOS_LIB_OBJ=$(patsubst %, $(SRC_BASE_PATH)/%, src/node/group.o src/node/pnode.o src/node/node.o src/node/propose_batch.o src/communicate/dfnetwork.o src/communicate/udp.o src/communicate/network.o src/communicate/communicate.o src/communicate/tcp/event_base.o src/communicate/tcp/message_event.o src/communicate/tcp/event_loop.o src/communicate/tcp/tcp_client.o src/communicate/tcp/tcp_acceptor.o src/communicate/tcp/notify.o src/communicate/tcp/tcp.o src/algorithm/base.o src/algorithm/proposer.o src/algorithm/acceptor.o src/algorithm/learner.o src/algorithm/learner_sender.o src/algorithm/instance.o src/algorithm/ioloop.o src/algorithm/commitctx.o src/algorithm/committer.o src/algorithm/checkpoint_sender.o src/algorithm/checkpoint_receiver.o src/algorithm/msg_counter.o src/checkpoint/cp_mgr.o src/checkpoint/replayer.o src/checkpoint/cleaner.o src/master/master_sm.pb.o src/master/master_sm.o src/master/master_mgr.o src/master/master_variables_store.o src/config/config.o src/config/system_v_sm.o src/sm-base/sm_base.o src/sm-base/sm.o src/logstorage/db.o src/logstorage/paxos_log.o src/logstorage/log_store.o src/logstorage/system_variables_store.o src/comm/paxos_msg.pb.o src/comm/breakpoint.o src/comm/options.o src/comm/inside_options.o src/comm/logger.o src/utils/concurrent.o src/utils/socket.o src/utils/util.o src/utils/crc32.o src/utils/timer.o src/utils/bytes_buffer.o src/utils/serial_lock.o src/utils/wait_lock.o src/utils/notifier_pool.o)
$(SRC_BASE_PATH)/.lib/extlib/libphxpaxos.a: $(PHXPAXOS_LIB_OBJ)
	ar -cvq $@ $(PHXPAXOS_LIB_OBJ)_

**Comment by andrewrong** [comment]
@xufangqing 这个是怎么样解决的？包括paxos_msg.pb.h这个文件找不到的问题？

**Comment by chinahbcq** [comment]
里面有个build.sh 直接执行就行

**Comment by jackwsl** [comment]
> @xufangqing 这个是怎么样解决的？包括paxos_msg.pb.h这个文件找不到的问题？

你好这个问题你解决了吗，我也遇到了这个问题
