### ISSUE TITLE
checkpoint_sender.cpp中的SendCheckpoint函数有重复代码

### ISSUE THREAD

**Issue by lichuang** [tencent-wechat/phxpaxos#51]
void CheckpointSender :: SendCheckpoint()
{
    int ret = m_poLearner->SendCheckpointBegin(
            m_iSendNodeID, m_llUUID, m_llSequence,
            m_poSMFac->GetCheckpointInstanceID(m_poConfig->GetMyGroupIdx()));
    if (ret != 0)
    {
        PLGErr("SendCheckpointBegin fail, ret %d", ret);
        return;
    }

    ret = m_poLearner->SendCheckpointBegin(
            m_iSendNodeID, m_llUUID, m_llSequence,
            m_poSMFac->GetCheckpointInstanceID(m_poConfig->GetMyGroupIdx()));
    if (ret != 0)
    {
        PLGErr("SendCheckpointBegin fail, ret %d", ret);
        return;
    }

这两段代码有重复吧？做的都是同一个事情。

**Comment by lynncui00** [comment]
这个是丑陋的代码，本意应该是调试的时候发现由于TCP连接重新建立的时候容易丢失第一条消息，所以简单重复了一下进行调试，后面可能就忘记去掉了。
