### ISSUE TITLE
为何SetMasterVariables、SetSystemVariables、SetMinChosenInstanceID总是同步写？

### ISSUE THREAD

**Issue by niukuo** [tencent-wechat/phxpaxos#53]
看起来参数中是有WriteOptions的，为何不用WriteOptions中的选项而是直接将bSync传true?
//而且看起来MasterStateMachine :: UpdateMasterToStore中已经设置了oWriteOptions.bSync = false;实际却并没有起作用？
请问这里是基于什么样的考虑？

**Comment by niukuo** [comment]
还有Database :: Put总是非同步写？

**Comment by lynncui00** [comment]
- MasterVariables和SystemVariables是要严格同步写的，这部分外面控制的代码属于冗余代码，适时可以去掉。
 - 针对PaxosLog的写盘分为两部分，一个是leveldb的索引，一个是vfile的实际内容，而索引是可以通过vfile进行恢复的，所以不需要同步写。

具体还可参考 [#45](https://github.com/tencent-wechat/phxpaxos/issues/45)
