### ISSUE TITLE
为什么存储数据的结构要设计成leveldb存储索引，文件存放数据？

### ISSUE THREAD

**Issue by lichuang** [tencent-wechat/phxpaxos#58]
为什么存储数据的结构要设计成leveldb存储索引，文件存放数据？而不是直接存放在leveldb里面。

**Comment by chenneal** [comment]
这里作者有过解释，主要有以下原因：

+ 如果直接用leveldb做存储，数据的compact开销会变得非常高，不合算。
+ 直接使用文件的一个好处是paxos log是顺序写，删除也是顺序删除。写入和或者删除的效率非变得非常高。
+ 增加索引的好处是能够快速的定位FileID，提升查找效率。
+ 因为索引的写入时非同步的，所以写索引和写盘2次动作和1次同步写盘没什么区别。
+ 索引非同步写可以根据vfile的内容恢复。

作者本人的解释见 #53 和 #45。
