### ISSUE TITLE
 请问一下什么情况下线程有可能被阻塞

### ISSUE THREAD

**Issue by xinmingyao** [tencent-wechat/phxpaxos#6]
使用phxpaxos后我们的服务好像线程被阻塞了，我们是主线程直接调用phxpaxos，有没法能够定位吗？比如加log之类的，谢谢

**Comment by lynncui00** [comment]
phxpaxos的propose接口在一下几种情况会进入阻塞等待。
1. 当前节点处于落后状态，需等待跟上并完成propose。
2. 当此propose出现网络超时等原因，一直处于重试状态。

解决办法：可以通过node.h里面的SetTimeout接口设置一个超时时间，在遇到以上两种情况会超时返回。

> 建议更新phxpaxos的代码到master最新，我们最近更新了一些过载保护相关的选项设置，还有对写盘性能以及数据安全进行了优化。
