### ISSUE TITLE
这么多错误，确定能编译过？

### ISSUE THREAD

**Issue by happyboy310** [tencent-wechat/phxpaxos#7]
g++ -std=c++11 -I/root/lvpy/lib/tencent/phxpaxos -I/usr/local/include/google/protobuf  -I/usr/include/leveldb -I/usr/local/include/glog  -Wall -g -fPIC -m64  -Wno-unused-local-typedefs -I/root/lvpy/lib/tencent/phxpaxos/include -I/root/lvpy/lib/tencent/phxpaxos/src/comm -I/root/lvpy/lib/tencent/phxpaxos/src/config -I/root/lvpy/lib/tencent/phxpaxos/src/logstorage -I/root/lvpy/lib/tencent/phxpaxos/src/master -I/root/lvpy/lib/tencent/phxpaxos/src/sm-base -I/root/lvpy/lib/tencent/phxpaxos/src/utils -I/usr/include/leveldb -I/usr/local/include/google/protobuf -Wall -Werror  -c -o master_variables_store.o master_variables_store.cpp
master_variables_store.cpp: In member function 'int phxpaxos::MasterVariablesStore::Write(const phxpaxos::WriteOptions&, int, const phxpaxos::MasterVariables&)':
master_variables_store.cpp:40:5: error: 'string' was not declared in this scope
     string sBuffer;
     ^
master_variables_store.cpp:40:5: note: suggested alternatives:
In file included from /usr/include/c++/4.8.2/string:39:0,
                 from master_variables_store.h:24,
                 from master_variables_store.cpp:22:
/usr/include/c++/4.8.2/bits/stringfwd.h:62:33: note:   'std::string'
   typedef basic_string<char>    string;
                                 ^
/usr/include/c++/4.8.2/bits/stringfwd.h:62:33: note:   'std::string'
master_variables_store.cpp:40:12: error: expected ';' before 'sBuffer'
     string sBuffer;
            ^
master_variables_store.cpp:41:48: error: 'sBuffer' was not declared in this scope
     bool sSucc = oVariables.SerializeToString(&sBuffer);
                                                ^
master_variables_store.cpp:44:43: error: 'PLG1Err' was not declared in this scope
         PLG1Err("Variables.Serialize fail");
                                           ^
master_variables_store.cpp:52:47: error: 'PLG1Err' was not declared in this scope
                 iGroupIdx, sBuffer.size(), ret);
                                               ^
master_variables_store.cpp:38:15: error: unused variable 'm_iMyGroupIdx' [-Werror=unused-variable]
     const int m_iMyGroupIdx = iGroupIdx;
               ^
master_variables_store.cpp: In member function 'int phxpaxos::MasterVariablesStore::Read(int, phxpaxos::MasterVariables&)':
master_variables_store.cpp:63:5: error: 'string' was not declared in this scope
     string sBuffer;
     ^
master_variables_store.cpp:63:5: note: suggested alternatives:
In file included from /usr/include/c++/4.8.2/string:39:0,
                 from master_variables_store.h:24,
                 from master_variables_store.cpp:22:
/usr/include/c++/4.8.2/bits/stringfwd.h:62:33: note:   'std::string'
   typedef basic_string<char>    string;
                                 ^
/usr/include/c++/4.8.2/bits/stringfwd.h:62:33: note:   'std::string'
master_variables_store.cpp:63:12: error: expected ';' before 'sBuffer'
     string sBuffer;
            ^
master_variables_store.cpp:64:61: error: 'sBuffer' was not declared in this scope
     int ret = m_poLogStorage->GetMasterVariables(iGroupIdx, sBuffer);
                                                             ^
master_variables_store.cpp:67:66: error: 'PLG1Err' was not declared in this scope
         PLG1Err("DB.Get fail, groupidx %d ret %d", iGroupIdx, ret);
                                                                  ^
master_variables_store.cpp:72:59: error: 'PLG1Imp' was not declared in this scope
         PLG1Imp("DB.Get not found, groupidx %d", iGroupIdx);
                                                           ^
master_variables_store.cpp:79:79: error: 'PLG1Err' was not declared in this scope
         PLG1Err("Variables.ParseFromArray fail, bufferlen %zu", sBuffer.size());
                                                                               ^
master_variables_store.cpp:61:15: error: unused variable 'm_iMyGroupIdx' [-Werror=unused-variable]
     const int m_iMyGroupIdx = iGroupIdx;
               ^
cc1plus: all warnings being treated as errors
make[1]: *** [master_variables_store.o] Error 1
make[1]: Leaving directory `/root/lvpy/lib/tencent/phxpaxos/src/master'
make[1]: Entering directory `/root/lvpy/lib/tencent/phxpaxos/src/node'
g++ -std=c++11 -I/root/lvpy/lib/tencent/phxpaxos -I/usr/local/include/google/protobuf  -I/usr/include/leveldb -I/usr/local/include/glog  -Wall -g -fPIC -m64  -Wno-unused-local-typedefs -I/root/lvpy/lib/tencent/phxpaxos/include -I/root/lvpy/lib/tencent/phxpaxos/src/algorithm -I/root/lvpy/lib/tencent/phxpaxos/src/checkpoint -I/root/lvpy/lib/tencent/phxpaxos/src/comm -I/root/lvpy/lib/tencent/phxpaxos/src/communicate -I/root/lvpy/lib/tencent/phxpaxos/src/communicate/tcp -I/root/lvpy/lib/tencent/phxpaxos/src/config -I/root/lvpy/lib/tencent/phxpaxos/src/logstorage -I/root/lvpy/lib/tencent/phxpaxos/src/master -I/root/lvpy/lib/tencent/phxpaxos/src/node -I/root/lvpy/lib/tencent/phxpaxos/src/sm-base -I/root/lvpy/lib/tencent/phxpaxos/src/utils -I/usr/include/leveldb -I/usr/local/include/google/protobuf -Wall -Werror  -c -o pnode.o pnode.cpp
In file included from pnode.cpp:22:0:
pnode.h:127:5: error: 'MultiDatabase' does not name a type
     MultiDatabase m_oDefaultLogStorage;
     ^
pnode.cpp: In member function 'int phxpaxos::PNode::InitLogStorage(const phxpaxos::Options&, phxpaxos::LogStorage*&)':
pnode.cpp:71:15: error: 'm_oDefaultLogStorage' was not declared in this scope
     int ret = m_oDefaultLogStorage.Init(oOptions.sLogStoragePath, oOptions.iGroupCount);
               ^
make[1]: *** [pnode.o] Error 1
make[1]: Leaving directory `/root/lvpy/lib/tencent/phxpaxos/src/node'
g++ -std=c++11 -I/root/lvpy/lib/tencent/phxpaxos -I/usr/local/include/google/protobuf  -I/usr/include/leveldb -I/usr/local/include/glog  -Wall -g -fPIC -m64  -Wno-unused-local-typedefs -I/root/lvpy/lib/tencent/phxpaxos/ -I/root/lvpy/lib/tencent/phxpaxos/include -I/root/lvpy/lib/tencent/phxpaxos/src/algorithm -I/root/lvpy/lib/tencent/phxpaxos/src/checkpoint -I/root/lvpy/lib/tencent/phxpaxos/src/comm -I/root/lvpy/lib/tencent/phxpaxos/src/communicate -I/root/lvpy/lib/tencent/phxpaxos/src/communicate/tcp -I/root/lvpy/lib/tencent/phxpaxos/src/config -I/root/lvpy/lib/tencent/phxpaxos/src/logstorage -I/root/lvpy/lib/tencent/phxpaxos/src/master -I/root/lvpy/lib/tencent/phxpaxos/src/node -I/root/lvpy/lib/tencent/phxpaxos/src/sm-base -I/root/lvpy/lib/tencent/phxpaxos/src/utils -I/usr/include/leveldb -I/usr/local/include/google/protobuf -Wall -Werror  -c -o /root/lvpy/lib/tencent/phxpaxos/src/node/pnode.o /root/lvpy/lib/tencent/phxpaxos/src/node/pnode.cpp
In file included from /root/lvpy/lib/tencent/phxpaxos/src/node/pnode.cpp:22:0:
/root/lvpy/lib/tencent/phxpaxos/src/node/pnode.h:127:5: error: 'MultiDatabase' does not name a type
     MultiDatabase m_oDefaultLogStorage;
     ^
/root/lvpy/lib/tencent/phxpaxos/src/node/pnode.cpp: In member function 'int phxpaxos::PNode::InitLogStorage(const phxpaxos::Options&, phxpaxos::LogStorage*&)':
/root/lvpy/lib/tencent/phxpaxos/src/node/pnode.cpp:71:15: error: 'm_oDefaultLogStorage' was not declared in this scope
     int ret = m_oDefaultLogStorage.Init(oOptions.sLogStoragePath, oOptions.iGroupCount);
               ^
make: *** [/root/lvpy/lib/tencent/phxpaxos/src/node/pnode.o] Error 1

**Comment by lynncui00** [comment]
编译命令没有问题，但src/comm/commdef.h的定义无法找到，请排查是否有其他环境问题，或由于设置了系统的-I导致某些头文件与系统存在的头文件重名。
