### ISSUE TITLE
选举功能编译问题

### ISSUE THREAD

**Issue by EawuChen** [tencent-wechat/phxpaxos#8]
你好，想请教个问题，如果想使用选举功能，编译时候应该指定哪些参数？谢谢。
比如像下面这样编译自带phxelection例子，就报错。
g++ -std=c++11 election.cpp election_main.cpp -I../include -L../lib/libphxpaxos.a

/tmp/ccvQw9HF.o：在函数‘phxelection::PhxElection::MakeLogStoragePath(std::string&)’中：
election.cpp:(.text+0x112)：对‘phxpaxos::NodeInfo::GetPort() const’未定义的引用
election.cpp:(.text+0x123)：对‘phxpaxos::NodeInfo::GetIP() const’未定义的引用
/tmp/ccvQw9HF.o：在函数‘phxelection::PhxElection::RunPaxos()’中：
election.cpp:(.text+0x2a4)：对‘phxpaxos::Options::Options()’未定义的引用
election.cpp:(.text+0x332)：对‘phxpaxos::GroupSMInfo::GroupSMInfo()’未定义的引用
election.cpp:(.text+0x37d)：对‘phxpaxos::Node::RunNode(phxpaxos::Options const&, phxpaxos::Node*&)’未定义的引用
/tmp/cc2h5vra.o：在函数‘parse_ipport(char const*, phxpaxos::NodeInfo&)’中：
election_main.cpp:(.text+0xac)：对‘phxpaxos::NodeInfo::SetIPPort(std::string const&, int)’未定义的引用
/tmp/cc2h5vra.o：在函数‘parse_ipport_list(char const*, std::vector<phxpaxos::NodeInfo, std::allocator<phxpaxos::NodeInfo> >&)’中：
election_main.cpp:(.text+0x1ba)：对‘phxpaxos::NodeInfo::NodeInfo()’未定义的引用
/tmp/cc2h5vra.o：在函数‘main’中：
election_main.cpp:(.text+0x2fb)：对‘phxpaxos::NodeInfo::NodeInfo()’未定义的引用
election_main.cpp:(.text+0x3f8)：对‘phxpaxos::NodeInfo::GetPort() const’未定义的引用
election_main.cpp:(.text+0x407)：对‘phxpaxos::NodeInfo::GetIP() const’未定义的引用
election_main.cpp:(.text+0x41e)：对‘phxpaxos::NodeInfo::GetNodeID() const’未定义的引用
collect2: error: ld returned 1 exit status

**Comment by lynncui00** [comment]
`-L`需要搭配`-l`使用，否则应去掉`-L`，另外还需要`libleveldb.a，libprotobuf.a`两个库，如果使用了glog打日志，则还需要一个`libphxpaxos_plugin.a`
建议在`sample/phxelection` 目录下面执行`make`，参考显示出来的g++命令。

**Comment by EawuChen** [comment]
搞错了，已经解决，谢谢。
