### ISSUE TITLE
内置选举功能一个疑问

### ISSUE THREAD

**Issue by EawuChen** [tencent-wechat/phxpaxos#9]
你好，请教个问题：
       如果节点的加入是通过类服务发现而逐渐加入，即任节点启动时并不知道其他节点的任何信息，直到通过服务发现才陆续知道其他节点的信息，而不是像你们给的例子是事先知道所有的节点ip，这个应该怎么实现呢？能否提供个大致思路呢？谢谢。

**Comment by lynncui00** [comment]
可以使用node.h里面的membership相关接口进行成员的添加，但必须有初始成员集合，并且由此集合向外扩展成员。但并不建议在成员变更非常频繁的节点集合上选举master，情况会较为复杂。
